services:

  backend:
    build: ../backend
    container_name: gamevault-api
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  frontend:
    build: ../frontend
    container_name: gamevault-web
    ports:
      - "4200:80"
    depends_on:
      - backend

  mongo:
    image: mongo:8
    container_name: gamevault-mongo
    restart: always
    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: